#include "nlx_parser_registry.h"

#include <string.h>

static const NlxParserDefinition nlx_parsers[] = {
    {"iso14443a",
     "ISO14443-A",
     NlxTechnologyNfc,
     NlxParserIntegrationNative,
     NlxToolBuiltInNfc,
     true,
     false},
    {"iso14443b",
     "ISO14443-B",
     NlxTechnologyNfc,
     NlxParserIntegrationNative,
     NlxToolBuiltInNfc,
     true,
     false},
    {"iso15693",
     "ISO15693",
     NlxTechnologyNfc,
     NlxParserIntegrationNative,
     NlxToolBuiltInNfc,
     true,
     false},
    {"felica",
     "FeliCa",
     NlxTechnologyNfc,
     NlxParserIntegrationNative,
     NlxToolBuiltInNfc,
     true,
     false},
    {"mifare-classic",
     "MIFARE Classic Mini/1K/4K",
     NlxTechnologyNfc,
     NlxParserIntegrationAdapter,
     NlxToolMfcEditor,
     true,
     false},
    {"mifare-ultralight",
     "MIFARE Ultralight/NTAG",
     NlxTechnologyNfc,
     NlxParserIntegrationAdapter,
     NlxToolBuiltInNfc,
     true,
     false},
    {"mifare-plus",
     "MIFARE Plus",
     NlxTechnologyNfc,
     NlxParserIntegrationAdapter,
     NlxToolBuiltInNfc,
     true,
     false},
    {"mifare-desfire",
     "MIFARE DESFire",
     NlxTechnologyNfc,
     NlxParserIntegrationAdapter,
     NlxToolBuiltInNfc,
     true,
     false},
    {"hid-h10301",
     "HID Prox H10301",
     NlxTechnologyLfRfid,
     NlxParserIntegrationNative,
     NlxToolBuiltInLfRfid,
     true,
     true},
    {"em4100",
     "EM4100",
     NlxTechnologyLfRfid,
     NlxParserIntegrationNative,
     NlxToolBuiltInLfRfid,
     true,
     false},
    {"indala",
     "Indala",
     NlxTechnologyLfRfid,
     NlxParserIntegrationNative,
     NlxToolBuiltInLfRfid,
     true,
     false},
    {"lf-generic",
     "Other firmware LF protocols",
     NlxTechnologyLfRfid,
     NlxParserIntegrationAdapter,
     NlxToolBuiltInLfRfid,
     true,
     false},
    {"picopass",
     "HID iCLASS/Picopass",
     NlxTechnologyPicopass,
     NlxParserIntegrationHandoff,
     NlxToolPicopass,
     false,
     false},
    {"ibutton",
     "Supported iButton/1-Wire",
     NlxTechnologyIbutton,
     NlxParserIntegrationNative,
     NlxToolBuiltInIbutton,
     true,
     false},
    {"transit",
     "Compatible transit/card parsers",
     NlxTechnologyNfc,
     NlxParserIntegrationHandoff,
     NlxToolMetroflip,
     false,
     false},
};

size_t nlx_parser_registry_count(void) {
    return sizeof(nlx_parsers) / sizeof(nlx_parsers[0]);
}

const NlxParserDefinition* nlx_parser_registry_get(size_t index) {
    return index < nlx_parser_registry_count() ? &nlx_parsers[index] : NULL;
}

const NlxParserDefinition* nlx_parser_registry_find(const char* id) {
    if(!id) return NULL;
    for(size_t i = 0U; i < nlx_parser_registry_count(); ++i) {
        if(strcmp(nlx_parsers[i].id, id) == 0) return &nlx_parsers[i];
    }
    return NULL;
}
